### ISSUE TITLE
Support for Key Votes

### ISSUE THREAD

**Issue by aaronrudkin** [JeffreyBLewis/Rvoteview#1]
Where relevant, the documentation and package should both support a field for key votes.

Format:
keyvote: 1

This will select only those votes that have a "key vote" field. We should discuss this to see if we want people to be able to isolate to key votes as determined by a particular organization (CQ at first, but presumably multiple organizations going forward).

**Comment by lukesonnet** [comment]
This will be implemented once we push the new schema, which I believe is going to be pre-launch.

**Comment by lukesonnet** [comment]
Implemented, documentation is another thing altogether.
