### ISSUE TITLE
Adding tooltips and decorations to member lists on vote pages

### ISSUE THREAD

**Issue by JeffreyBLewis** [JeffreyBLewis/Rvoteview#12]
We need to spice up the member lists on the vote pages and probably on the congress/senate pages in the following ways:

(1) When sorted by ideology, we should have a tooltip that shows the 1st dim nominate score on roll over.

(2) When sort by vote probability, we should have tooltip that shows the prob of a yea vote for each member.

(3) When sorted by ideology we should decorate the median member as well as the veto override pivot and the fillabuster pivots (senate only of course for that one).

**Comment by aaronrudkin** [comment]
I think this was probably intended for WebVoteView? But this all seems good.

**Comment by adamboche** [comment]
This issue was moved to JeffreyBLewis/WebVoteView#94
