### ISSUE TITLE
Nominate scores do not change over time

### ISSUE THREAD

**Issue by jaytimm** [JeffreyBLewis/Rvoteview#24]
Hi. I am a big VoteView fan, and have just started playing some with your package. Just a couple of questions (that are likely more generally VoteView-related questions).

Lawmakers are assigned a single set of nominate scores (1d & 2d) for their entire political careers, across multiple Congresses and even if they move from the House to the Senate, for example.  

How are these scores calculated across multiple congresses? And is there a way to access a lawmaker's political ideology scores for a specific congress via `Rvoteview` (without re-running a model)?  Presumably a lawmaker's ideologies can change over time. 

Thanks.

**Comment by adamboche** [comment]
Hi @jaytimm. Thanks for your interest. The [Nokken Poole scores](https://voteview.com/data) on our data page are estimated congress-by-congress. I hope that helps!

**Comment by jaytimm** [comment]
Wonderful. Thank you.  Accessing these scores via Rvoteview would be a nice feature.
